### PR TITLE
Add debug.printNodeTree

### PR DESCRIPTION
**Pull request by tewlwolow**
A small helper function to print node structure for a `niNode` objects for testing. Super useful for working with root nodes.

### CODE REVIEW

**Comment by C3pa** [comment]
I am glad to see some contributions. I like that the tree is printed with indentation so it is easy to see parent nodes. One request only: the documentation is now built from the definition files. So, [autocomplete/definitions/global/debug/printNodeTree.lua](https://github.com/MWSE/MWSE/pull/367/files#diff-e34a5c568f5ede3dcff44f2c1469c0dfb000d5ea4092ab68818575f91b51234d) was a definition file. The .md file and lua file with EmmyLua annotations are automatically generated by our documentation build system. You can see how to do so by searching history in #mwse channel on our discord server. 

In addition, since debug.md is automatically generated, you need to add all your descriptions to debug.lua denition file. See how to add a code example [here](https://github.com/MWSE/MWSE/blob/master/docs/function-definitions-guide.md).

**Comment by tewlwolow** [comment]
Many thanks for clarification C3pa.

As discussed on Discord, this would rather be generalised into a proper C++-side traverse sort of function with tree printing as optional param.

I'll eventually get to it :)

**Comment by C3pa** [comment]
We already have a [table.traverse](https://mwse.github.io/MWSE/apis/table/#tabletraverse) implemented  in lua. Feel free to add your solution.

**Comment by tewlwolow** [comment]
Closing this one as `table.traverse` + `ssg` is more than enough for now.

**Pull request closed without merging**
