### PR TITLE
fixed bugs in `mwse.loadConfig`

### PR DESCRIPTION
**Pull request by herbertgithubaccount**
1) default values are now copied into subtables with integer indices. 
 - this wasn't happening in the current version because the old implementation would first call `table.copymissing`, and then call `restoreIntegerKeys`.
 - heres an example to illustrate the problem:
   - lets say the config loaded by `json.loadfile` is named `result`, and the default config is named `defaults`.
   - lets say `defaults` has a subtable `defaults[3] = {key1 = value1, key2 = value2}`. 
   - lets say the corresponding subtable in `results` is missing an entry for `key2`.
   - then `results` would get loaded as `results["3"] = {key1 = somevalue}` (string keys have not been converted yet)
   - afterwards, `table.copymissing` would get called, notice that the index `[3]` is missing from `results`, and then `results` would look like `{ [3] = {key1 = value1, key2 = value3}, ["3"] = {key1 = somevalue} }`.
   - now, `restoreIntegerKeys` would be called, and it would notice that the index `"3"` should really be `3`.
   - afterwards, results would look like `{ [3] = {key1 = somevalue }`.
2) `mwse.loadConfig` will now return a `deepcopy` of the defaults table if no json config could be loaded (this is so that users dont end up editing the default config by mistake)

EDIT: its not sufficient to just swap the order, this causes problems on empty tables. a deeper fix is needed. i'm working on it now
EDIT 2: things should be good now

### CODE REVIEW

**Comment by C3pa** [comment]
I added some tests for this functionality in https://github.com/MWSE/MWSE/commit/b31c7151e1a9128a38174f19caa437a39443570f. To run these tests, run Morrowind with --core_tests mwseLoadConfig.

The last added test is from your description. It's failing in master (as expected), but it's passing in this PR.

**Comment by C3pa** [comment]
Do you know of any mods that were broken because of this?

**Comment by herbertgithubaccount** [comment]
> Do you know of any mods that were broken because of this?

That's a bit of a hard question to answer, because I think this bug mainly affects mods that update their config structure. So, it theoretically shouldn't be possible to detect in current version of any mods source code. 

But since it's so specific, it can be really hard to pinpoint the cause some weird bugs. I ran into this bug when working on my upcoming character progression mod. I was storing subtables indexed by `tes3.skill` ids, and during the internal development I wanted to add a few keys to these subtables, but they only got added if I deleted the pre-existing config file.

**Comment by C3pa** [comment]
Thanks for fixing this Herbert!

**Pull request merged**
