### PR TITLE
Proposed fix for warning in mwse_init.lua

### PR DESCRIPTION
**Pull request by C3pa**
Fix a warning in mwse_init.lua and disable warnings for the others. The goal is to reduce the number of warnings generated by MWSE files users get when they open MWSE folder as a workspace.

### CODE REVIEW

**Comment by C3pa** [comment]
To fix the most of them I could just add 
```Lua
	file:write("--- @diagnostic disable\n\n")
```
to line 168 in `emmy.lua`. What do you think about this? 

Despite annoying, these warnings list which definitions we are missing, but in the huge sea of around a hundred warnings, it's just hard to find which ones come from your code.

**Comment by NullCascade** [comment]
Yeah it serves some of a purpose but it's probably better to do what you suggest. We can help ourselves later, this is supposed to be better for not developers. Go for it.

**Comment by C3pa** [comment]
I decided to put all the warnings in a file and made #343 so we can track those warnings.

So, a brief summary of recent changes:

1. Added `--- @diagnostic disable:undefined-global` to `main.lua` for MWSE's MCM to hide `"Undefined global `mwseConfig`."`
2. Added `---@diagnostic disable-next-line:undefined-global` to hide `"Undefined global `mwseDisableableEventManager`."` in event.lua
3. I stayed conservative so I added `file:write("--- @diagnostic disable:undefined-doc-name\n\n")` to `emmy.lua`, which should just hide warnings coming from missing definitions. Other warnings are still there.
4. Rebuilt the documentation with new change in emmy.lua

**Comment by C3pa** [comment]
Could you update luasocket? If I am reading correctly, this [line](https://github.com/lunarmodules/luasocket/blob/88c8a85cb6528232288ec590910b7a966aace52b/src/url.lua#L240) should fix 2 warnings we get:
[{
	"resource": "/c:/Users/Vlasnik/MWSE/misc/package/Data Files/MWSE/core/lib/socket/url.lua",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "lowercase-global",
	"severity": 2,
	"message": "Global variable in lowercase initial, Did you miss `local` or misspell it?",
	"source": "Lua Diagnostics.",
	"startLineNumber": 223,
	"startColumn": 9,
	"endLineNumber": 223,
	"endColumn": 20
},{
	"resource": "/c:/Users/Vlasnik/MWSE/misc/package/Data Files/MWSE/core/lib/socket/url.lua",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "lowercase-global",
	"severity": 2,
	"message": "Global variable in lowercase initial, Did you miss `local` or misspell it?",
	"source": "Lua Diagnostics.",
	"startLineNumber": 226,
	"startColumn": 9,
	"endLineNumber": 226,
	"endColumn": 20
}]

**Pull request merged**
