### PR TITLE
tes3npc and tes3npcInstance doc updates.

### PR DESCRIPTION
**Pull request by Merzasphor**
Added missing properties and other minor fixes.

First attempt with the new doc structure. I think I generated everything that needed to be, but let me know if I've left something out.

### CODE REVIEW

**Comment by C3pa** [comment]
Hi, you generated all the needed files. 

If you want, you can also add the `deprecated = true,` field to the definitions. That way those won't show up in the generated .md files. As for the autocomplete files, it behaves differently based on the type of the definitions. For example, a deprecated flag for a property on a type will remove the property from the autocomplete files, while for the library definitions, you'll still have autocomplete files, but using those will make them marked as deprecated.

image

**Comment by C3pa** [comment]
Thanks!

**Comment by Merzasphor** [comment]
Is that the preferred way to handle deprecated items? For properties on a type, setting that flag appears to have the same effect as just removing the property.lua file.

**Comment by C3pa** [comment]
Well, we don't have an agreement on how to handle properties, and there are not a lot of single deprecated properties. But, one bigger portion of the deprecated API is the mwscript API. In that case, it is not intended to have it removed from the documentation since some edge cases don't work exactly the same as their counterparts in the tes3 API, so there are quite a few people still using it. We can have a discussion with other contributors over at discord about this.

As for the deprecated flag on the property of a type, you are right. It is effectively the same as removing the file.

**Pull request merged**
