### PR TITLE
extend `table` some more

### PR DESCRIPTION
**Pull request by herbertgithubaccount**
~~still needs docs and bug testing~~

### functional programming stuff
* `map(t, f)`: applies a `function` `f` to everything in the `table` `t`.
* `filter(t, f)`: only keeps the values `v` of `t` for which `f` returns `f(v)` is not `nil` or `false`
* `filterarray(t, f)`: like `filter`, but it works properly for arrays. (i.e., it's powered by `table.insert`.
* ~~`sub(t, i, j, step)`:~~ returns a subarray of `t`, starting at index `i` and ending at index `j`; `step` takes on the same meaning as it would in the statement `for k = i, j, step`.
  * all of `i`, `j`, and `step` can be negative. if `i` or `j` is negative, then that index will be wrapped (as it would via `table.wrapindex`). if `step` is negative, then the table will be iterated in reverse order, as in the statement `for k = i, j , step`

### other stuff (these ones are more questionable probably)
* ~~`append(tbl, ...)`:~~ this is like `copy`, but for copying multiple tables at a time.
*  ~~`deepappend(tbl, ...)`:~~ like `deepcopy`, but for deepcopying multiple tables at a time. with one key difference though: you can now `deepcopy` one `table` into another `table`.
* ~~`appendmissing`:~~ this is `copymissing` for multiple tables at a time.
* ~~`combine(...)`:~~ this one "combines" a bunch of tables. i.e., it's basically just
```lua
function table.combine(...)
    local tbl = {}
    table.append(tbl, ...)
    return tbl
end
```

### CODE REVIEW

**Comment by C3pa** [comment]
We reached a conclusion: let's get the `table.map` and `table.filter` in. Can you add docs for those 2? We can do that in this PR or a new one, whichever is simpler.

**Comment by herbertgithubaccount** [comment]
i can make the changes in this one. should i keep the `filterarray` function as well as `filter`? 

i worry that only having `filter` would break the functionality on array-style tables. (if a value in the middle of the array gets filtered out, then `ipairs` and `__len` would ignore all subsequent values)

**Comment by C3pa** [comment]
Yeah, I see. Holes in Lua arrays can trip people up (I tripped there a lot of times). What do you think if we overloaded `table.filter` to behave roughly as:
```lua
function table.filter(t, f)
    -- Non continuous array or table with hash part?
    if #t ~= table.size(t) do
        -- do current table.filter
    else
        -- do what table.filterarray does
    end
end
```
Would that be to smart for its own good?

**Comment by C3pa** [comment]
Thanks Herbert!

**Pull request merged**
