### PR TITLE
Implement definition check

### PR DESCRIPTION
**Pull request by C3pa**
Here I propose a new task that performs the following checks on our autocomplete/definitions files and writes them to the warnings.txt file in autocomplete folder:
 - Missing descriptions
 - An argument in a function/method definition has a `default` field set but hasn't got `optional`.

Here is the current output:
[warnings.zip](https://github.com/MWSE/MWSE/files/9173742/warnings.zip)

### CODE REVIEW

**Comment by pierresteeg** [comment]
I have not yet looked at the implementation. Im not sure if intended, but our built docs do not list that something is optional and only lists the default value if both are present. Personally, im for including the `Optional.` output even if we have a default set.

Depending on what we want to regarding that Id just error out instead of printing warnings and include it directly in the build process instead of a separate step.

**Comment by C3pa** [comment]
>  Im not sure if intended, but our built docs do not list that something is optional and only lists the default value if both are present. Personally, im for including the Optional. output even if we have a default set.
Primarily, I wanted to add the checks for optional without default to fix the issue that I described in #377, which only affects emmylua annotations. We can also include "Optional" in the descriptions on the online version of the documentation.

> Depending on what we want to do regarding that Id just error out instead of printing warnings and include it directly in the build process instead of a separate step.
What do you exactly mean by this? Should I call error() lua function directly to "error"? Also, would you prefer if I added this directly to one of the existing builders so it will occur on any build?

**Comment by C3pa** [comment]
> The description warnings seem fine to me, there are lots of empty description fields.

Keep in mind I didn't make it check for missing descriptions on function arguments. I'd say that would make the list explode, and the descriptions for those aren't always necessary.

**Comment by pierresteeg** [comment]
> What do you exactly mean by this? Should I call error() lua function directly to "error"? Also, would you prefer if I added this directly to one of the existing builders so it will occur on any build?

If we want to define definitions that include `default` but not `optional` as invalid then I'd error, yes.

**Comment by C3pa** [comment]
@pierresteeg I addressed your concerns like this:
1.) Integrated the check for missing `optional = true` flag in the method and function definitions arguments into the `builders\common.lua`.
2.) Moved the logic for finding definitions with missing descriptions to `builders\youforgotsomething.lua`. Also, I added a task and brief info on using that file. All the results are logged to the terminal (as that file worked before). Here is its [output](https://github.com/MWSE/MWSE/files/9389608/output.txt) with `FIND_MISSING_DESCRIPTIONS = true`, and `CHECK_ARGUMENT_DESCRIPTION = false`.
3.) Removed the `definitionCheck.lua`

**Comment by C3pa** [comment]
I don't like this in our documentation-building process.

**Pull request closed without merging**
