### PR TITLE
Add uiSkillTooltip event.

### PR DESCRIPTION
**Pull request by Petethegoat**
~~Still needs doc, autocomplete, and testing~~

Still needs testing. Uses numbers for the tooltip type and maybe that should be a bool or a named table thing.

### CODE REVIEW

**Comment by C3pa** [comment]
What's with the `lpeg.dll`?

**Comment by Petethegoat** [comment]
> What's with the `lpeg.dll`?

Misclick. Will remove it.

**Comment by C3pa** [comment]
Mind adding this event to `tes3.event` table, and to [reference/events.md](https://github.com/MWSE/MWSE/blob/master/docs/source/references/events.md)?

**Comment by Petethegoat** [comment]
> Mind adding this event to `tes3.event` table, and to [reference/events.md](https://github.com/MWSE/MWSE/blob/master/docs/source/references/events.md)?

Let me know if this look right, thanks!

**Comment by C3pa** [comment]
Yes, your docs are spot on. Thanks!

**Pull request merged**
