### PR TITLE
Added more bindings for NiNode, NiDynamicEffect, and NiTextureEffect.

### PR DESCRIPTION
**Pull request by OperatorJack**

### CODE REVIEW

**Comment by OperatorJack** [comment]
In Lua, `.sourceTexture` is not found on a `niTextureEffect`.

**Comment by OperatorJack** [comment]
Sample lua code:
```lua
function key(e)
  if (e.keyCode == tes3.scanCode.p and e.isAltDown == true) then
    if (tes3.worldController.enchantedItemEffectCreated ~= true) then
      tes3.messageBox("Enchanted Item Texture not created yet! Oh no.")
    end

    local textureEffect = tes3.worldController.enchantedItemEffect:clone()
    if( textureEffect) then
      local newTextureFilepath = "Textures\\tx_bm_iceberg.dds"
      textureEffect.sourceTexture = niSourceTexture.createFromPath(newTextureFilepath)

      for ref in tes3.player.cell:iterateReferences() do
        ref.sceneNode:attachEffect(textureEffect)
        ref.sceneNode:update()
        ref.sceneNode:updateEffects()
        tes3.messageBox("Shiny!")
      end
    end
  end
end

event.register("key", key)
```

**Comment by NullCascade** [comment]
Why is lpeg updated with this? Just from a different compiler?

**Comment by Merzasphor** [comment]
There's no need to add lpeg.dll to the repo. It's built automatically from source and added to the package for distribution.

**Pull request merged**
